### ISSUE TITLE
Multiple Reports for same day starts at 08:00

### ISSUE THREAD

**Issue by GrundstromT** [Schillman/AutoToggl#1]
When I add multiple reports per day all of them starts at 08:00.

It would be nice to be able to specify start time for the different reports.

**Comment by Schillman** [comment]
There is a couple of solutions to this problem.

- We append them to the day, so first entry on a given day would start from 8 AM but the second entry continues after the first one and so forth. 
This would utilise the already available parameter 'durationInHours'

Or

- We could as you mentioned let the user specify a time range. So two new parameters would be added ex 'starTime & endTime' on each customer entry.
This would be a more flexible solution. And also be implemented for other days wherr only 1 entry was specified. So one could specify when I start work for any given day.
Some maybe start their day at 9 AM  to 6 PM on Mondays but on Tuesday they work 8 AM to 12 AM...
Another benefit of this would mean that we could remove the parameter 'fullDayHours' and calculate the hours striven for each day.

**Comment by Schillman** [comment]
Added a config parameter that will let you specify when the entry should start. This should solve the issue at hand, but the question still stands whether we'd like to specify a time range.
